diseases/urls.py
from django.urls import path
from . import views

app_name = 'diseases'

urlpatterns = [
    path('', views.disease_list, name='disease_list'),
    path('<int:pk>/', views.disease_detail, name='disease_detail'),
]

doctors/urls.py
from django.urls import path
from . import views

app_name = 'doctors'

urlpatterns = [
    path('', views.doctor_list, name='doctor_list'),
    path('<int:pk>/', views.doctor_detail, name='doctor_detail'),
]

heartcenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('', views.home, name='home'),
    # path('diseases/', include('diseases.urls', namespace='diseases')),
    # path('medications/', include('medications.urls', namespace='medications')),
    # path('supplements/', include('supplements.urls', namespace='supplements')),
    # path('doctors/', include('doctors.urls', namespace='doctors')),
]

urlpatterns += i18n_patterns(
    path('', views.home, name='home'),  # Your home view
    path('diseases/', include('diseases.urls', namespace='diseases')),
    path('medications/', include('medications.urls', namespace='medications')),
    path('supplements/', include('supplements.urls', namespace='supplements')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('search/', include('search.urls', namespace='search')),
)

medications/urls.py
from django.urls import path
from . import views

app_name = 'medications'

urlpatterns = [
    path('', views.medication_list, name='medication_list'),
    path('<int:pk>/', views.medication_detail, name='medication_detail'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'medications'

urlpatterns = [
    path('', views.search, name='search'),
]

supplements/urls.py
from django.urls import path
from . import views

app_name = 'supplements'

urlpatterns = [
    path('', views.supplement_list, name='supplement_list'),
    path('<int:pk>/', views.supplement_detail, name='supplement_detail'),
]

diseases/models.py
from django.db import models

from heartcenter.settings import LANGUAGE_CHOICES

class Disease(models.Model):
    name = models.CharField(max_length=255, unique=True)
    text = models.TextField()
    lang = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    def __str__(self):
        return self.name

doctors/models.py
from django.db import models
from django.conf import settings

from heartcenter.settings import LANGUAGE_CHOICES

class Doctor(models.Model):
    name = models.CharField(max_length=255, unique=True)
    text = models.TextField()
    lang = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    def __str__(self):
        return self.name

medications/models.py
from django.db import models

from heartcenter.settings import LANGUAGE_CHOICES

class Medication(models.Model):
    name = models.CharField(max_length=255, unique=True)
    text = models.TextField()
    lang = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    def __str__(self):
        return self.name

supplements/models.py
from django.db import models

from heartcenter.settings import LANGUAGE_CHOICES

class Supplement(models.Model):
    name = models.CharField(max_length=255, unique=True)
    text = models.TextField()
    lang = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    def __str__(self):
        return self.name

diseases/views.py
# diseases/views.py

import markdown2
from django.shortcuts import render, get_object_or_404
from django.utils.translation import get_language
from django.utils.safestring import mark_safe
from .models import Disease

def disease_list(request):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]    
    diseases = Disease.objects.filter(lang=current_lang)
    return render(request, 'diseases/disease_list.html', {'diseases': diseases})

def disease_detail(request, pk):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    disease = get_object_or_404(Disease, pk=pk, lang=current_lang)
    disease.text = mark_safe(markdown2.markdown(disease.text))

    if 'HX-Request' in request.headers:
        template_name = 'diseases/partials/disease_detail_partial.html'
    else:
        template_name = 'diseases/disease_detail.html'
    
    return render(request, template_name, {'disease': disease})

doctors/views.py
import markdown2
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
from django.utils.translation import get_language
from .models import Doctor

def doctor_list(request):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    doctors = Doctor.objects.filter(lang=current_lang)
    return render(request, 'doctors/doctor_list.html', {'doctors': doctors})

def doctor_detail(request, pk):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    doctor = get_object_or_404(Doctor, pk=pk, lang=current_lang)
    doctor.text = mark_safe(markdown2.markdown(doctor.text))
    if 'HX-Request' in request.headers:
        template_name = 'doctors/partials/doctor_detail_partial.html'
    else:
        template_name = 'doctors/doctor_detail.html'
    
    return render(request, template_name, {'doctor': doctor})

heartcenter/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

medications/views.py
import markdown2
from django.shortcuts import render, get_object_or_404
from django.utils.translation import get_language
from django.utils.safestring import mark_safe
from .models import Medication

def medication_list(request):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    medications = Medication.objects.filter(lang=current_lang)
    return render(request, 'medications/medication_list.html', {'medications': medications})

def medication_detail(request, pk):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    medication = get_object_or_404(Medication, pk=pk, lang=current_lang)
    medication.text = mark_safe(markdown2.markdown(medication.text))
    if 'HX-Request' in request.headers:
        template_name = 'medications/partials/medication_detail_partial.html'
    else:
        template_name = 'medications/medication_detail.html'
    
    return render(request, template_name, {'medication': medication})

search/views.py
from django.shortcuts import render
from django.db.models import Q
from diseases.models import Disease
from medications.models import Medication
from supplements.models import Supplement
from doctors.models import Doctor

def search(request):
    query = request.GET.get('q')
    diseases = Disease.objects.filter(name__icontains=query) if query else []
    medications = Medication.objects.filter(name__icontains=query) if query else []
    supplements = Supplement.objects.filter(name__icontains=query) if query else []
    doctors = Doctor.objects.filter(name__icontains=query) if query else []

    context = {
        'query': query,
        'diseases': diseases,
        'medications': medications,
        'supplements': supplements,
        'doctors': doctors,
    }
    return render(request, 'search/search_results.html', context)

supplements/views.py
import markdown2
from django.shortcuts import render, get_object_or_404
from django.utils.translation import get_language
from django.utils.safestring import mark_safe
from .models import Supplement

def supplement_list(request):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    print(current_lang, '####')
    supplements = Supplement.objects.filter(lang=current_lang)
    return render(request, 'supplements/supplement_list.html', {'supplements': supplements})

def supplement_detail(request, pk):
    current_lang = get_language()
    current_lang = current_lang.split('-')[0]
    supplement = get_object_or_404(Supplement, pk=pk, lang=current_lang)
    supplement.text = mark_safe(markdown2.markdown(supplement.text))
    if 'HX-Request' in request.headers:
        template_name = 'supplements/partials/supplement_detail_partial.html'
    else:
        template_name = 'supplements/supplement_detail.html'
    
    return render(request, template_name, {'supplement': supplement})

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_CODE == 'fa' %}rtl{% else %}ltr{% endif %}">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% trans "Heart Center" %}{% endblock %}</title>
    <!-- Include Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <!-- Include custom styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Include htmx -->
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
</head>
<body>
    <!-- Sidebar Toggle Button -->
    <button id="sidebarToggle" class="sidebar-toggle" aria-label="{% trans 'Toggle Sidebar' %}">
        <i class="fas fa-chevron-right" id="toggleIcon"></i>
    </button>

    <!-- Header with Search Bar -->
    <header class="header">
        <form method="GET" action="{% url 'search:search' %}" class="search-bar">
            <input type="text" name="q" placeholder="{% trans 'Search...' %}" value="{{ request.GET.q }}">
            <button type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
    </header>

    <div class="container">
        <div class="content" id="content">
            {% block content %}{% endblock %}
        </div>
        <div class="sidebar" id="sidebar">
            <!-- Sidebar content -->
            <div class="language-switcher">
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ request.path }}">
                    {% if LANGUAGE_CODE == 'en' %}
                    <button type="submit" name="language" value="fa">{% trans "Switch to Persian" %}</button>
                    {% else %}
                    <button type="submit" name="language" value="en">{% trans "Switch to English" %}</button>
                    {% endif %}
                </form>
            </div>
            <h2>{% trans "Categories" %}</h2>
            <ul>
                <li><a href="{% url 'diseases:disease_list' %}">{% trans "Diseases" %}</a></li>
                <li><a href="{% url 'medications:medication_list' %}">{% trans "Medications" %}</a></li>
                <li><a href="{% url 'supplements:supplement_list' %}">{% trans "Supplements" %}</a></li>
                <li><a href="{% url 'doctors:doctor_list' %}">{% trans "Doctors" %}</a></li>
            </ul>
            <div id="sidebar-content">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </div>

    <!-- JavaScript to handle the toggle -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const toggleButton = document.getElementById('sidebarToggle');
        const toggleIcon = document.getElementById('toggleIcon');

        toggleButton.addEventListener('click', function() {
            document.body.classList.toggle('sidebar-hidden');
            document.body.classList.toggle('sidebar-active');
            // Change the icon based on the sidebar state
            if (document.body.classList.contains('sidebar-active')) {
                toggleIcon.classList.remove('fa-times');
                toggleIcon.classList.add('fa-bars'); /* Use 'bars' icon to indicate menu */
            } else {
                toggleIcon.classList.remove('fa-bars');
                toggleIcon.classList.add('fa-times'); /* Use 'times' icon to indicate close */
            }
        });
    });
</script></body>
</html>

templates/diseases/disease_detail.html
{% extends 'base.html' %}

{% block title %}{{ disease.name }}{% endblock %}

{% block content %}
<h2>{{ disease.name }}</h2>
<p>{{ disease.text }}</p>
{% endblock %}

templates/diseases/disease_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Disease List" %}{% endblock %}

{% block sidebar%}
    <ul>
        {% for disease in diseases %}
            <li>
                <a 
                  hx-get="{% url 'diseases:disease_detail' disease.pk %}" 
                  hx-target="#content" 
                  hx-swap="innerHTML">
                    {{ disease.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/diseases/diseases_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ disease.name }}</title>
</head>
<body>
    <h1>{{ disease.name }}</h1>
    <p><strong>Description:</strong> {{ disease.description }}</p>
    <p><strong>Symptoms:</strong> {{ disease.symptoms }}</p>
    <p><strong>Treatments:</strong> {{ disease.treatments }}</p>
    <a href="{% url 'diseases:disease_list' %}">Back to list</a>
</body>
</html>

templates/diseases/diseases_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Disease List</title>
</head>
<body>
    <h1>Diseases</h1>
    <ul>
        {% for disease in diseases %}
            <li><a href="{% url 'diseases:disease_detail' disease.pk %}">{{ disease.name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/diseases/partials/disease_detail_partial.html
<p>{{ disease.text }}</p>

templates/doctors/doctor_detail.html
{% extends 'base.html' %}

{% block title %}{{ disease.name }}{% endblock %}

{% block content %}
<h2>{{ doctor.name }}</h2>
<p>{{ doctor.text|markdown }}</p>
{% endblock %}

templates/doctors/doctor_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Doctor List" %}{% endblock %}

{% block sidebar%}
    <ul>
        {% for doctor in doctors %}
            <li>
                <a 
                  hx-get="{% url 'doctor:doctor_detail' doctor.pk %}" 
                  hx-target="#content" 
                  hx-swap="innerHTML">
                    {{ doctor.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/doctors/doctors_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ doctor.name }}</title>
</head>
<body>
    <h1>{{ doctor.name }}</h1>
    <p><strong>Specialty:</strong> {{ doctor.specialty }}</p>
    <p><strong>Contact Info:</strong> {{ doctor.contact_info }}</p>
    <a href="{% url 'doctors:doctor_list' %}">Back to Doctor List</a>
</body>
</html>

templates/doctors/doctors_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Doctor List</title>
</head>
<body>
    <h1>Doctors</h1>
    <ul>
        {% for doctor in doctors %}
            <li>
                <a href="{% url 'doctors:doctor_detail' doctor.pk %}">{{ doctor.name }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/doctors/partials/doctor_detail_partial.html
<p>{{ doctor.text }}</p>

templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Heart Center" %}{% endblock %}

{% block content %}
    <h1>{% trans "Welcome to the Heart Center" %}</h1>
    <p>{% trans "Select a section to explore:" %}</p>
    <ul>
        <li><a href="{% url 'diseases:disease_list' %}">{% trans "Diseases" %}</a></li>
        <li><a href="{% url 'medications:medication_list' %}">{% trans "Medications" %}</a></li>
        <li><a href="{% url 'supplements:supplement_list' %}">{% trans "Supplements" %}</a></li>
        <li><a href="{% url 'doctors:doctor_list' %}">{% trans "Doctors" %}</a></li>
    </ul>
{% endblock %}

templates/medications/medication_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ medication.name }}</title>
</head>
<body>
    <p> {{ medication.text }}</p>
    <a href="{% url 'medications:medication_list' %}">Back to Medication List</a>
</body>
</html>

templates/medications/medication_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Medication List" %}{% endblock %}

{% block sidebar%}
    <ul>
        {% for medication in medications %}
            <li>
                <a 
                  hx-get="{% url 'medications:medication_detail' medication.pk %}" 
                  hx-target="#detail" 
                  hx-swap="innerHTML">
                    {{ medication.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{% block content %}
    <div id="detail"></div>
{% endblock %}

templates/medications/medications_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ medication.name }}</title>
</head>
<body>
    <h1>{{ medication.name }}</h1>
    <p><strong>Description:</strong> {{ medication.description }}</p>
    <p><strong>Uses:</strong> {{ medication.uses }}</p>
    <p><strong>Side Effects:</strong> {{ medication.side_effects }}</p>
    <a href="{% url 'medications:medication_list' %}">Back to Medication List</a>
</body>
</html>

templates/medications/medications_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Medication List</title>
</head>
<body>
    <h1>Medications</h1>
    <ul>
        {% for medication in medications %}
            <li>
                <a href="{% url 'medications:medication_detail' medication.pk %}">{{ medication.name }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/medications/partials/medication_detail_partial.html
<p>{{ medication.text }}</p>

templates/search/search_results.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Search Results" %}{% endblock %}

{% block content %}
    <h1>{% trans "Search Results for" %} "{{ query }}"</h1>

    {% if diseases %}
        <h2>{% trans "Diseases" %}</h2>
        <ul>
            {% for disease in diseases %}
                <li><a href="{% url 'diseases:disease_detail' disease.pk %}">{{ disease.name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if medications %}
        <h2>{% trans "Medications" %}</h2>
        <ul>
            {% for medication in medications %}
                <li><a href="{% url 'medications:medication_detail' medication.pk %}">{{ medication.name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if supplements %}
        <h2>{% trans "Supplements" %}</h2>
        <ul>
            {% for supplement in supplements %}
                <li><a href="{% url 'supplements:supplement_detail' supplement.pk %}">{{ supplement.name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if doctors %}
        <h2>{% trans "Doctors" %}</h2>
        <ul>
            {% for doctor in doctors %}
                <li><a href="{% url 'doctors:doctor_detail' doctor.pk %}">{{ doctor.name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if not diseases and not medications and not supplements and not doctors %}
        <p>{% trans "No results found." %}</p>
    {% endif %}
{% endblock %}

templates/supplements/partials/supplement_detail_partial.html
<p>{{ supplement.text }}</p>

templates/supplements/supplement_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ supplement.name }}</title>
</head>
<body>
    <p> {{ supplement.text }}</p>
    <a href="{% url 'supplements:supplement_list' %}">Back to Supplement List</a>
</body>
</html>

templates/supplements/supplement_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Supplement List" %}{% endblock %}

{% block sidebar%}
    <ul>
        {% for supplement in supplements %}
            <li>
                <a 
                  hx-get="{% url 'supplements:supplement_detail' supplement.pk %}" 
                  hx-target="#content" 
                  hx-swap="innerHTML">
                    {{ supplement.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/supplements/supplements_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ supplement.name }}</title>
</head>
<body>
    <h1>{{ supplement.name }}</h1>
    <p><strong>Description:</strong> {{ supplement.description }}</p>
    <p><strong>Benefits:</strong> {{ supplement.benefits }}</p>
    <p><strong>Side Effects:</strong> {{ supplement.side_effects }}</p>
    <a href="{% url 'supplements:supplement_list' %}">Back to Supplement List</a>
</body>
</html>

templates/supplements/supplements_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Supplement List</title>
</head>
<body>
    <h1>Supplements</h1>
    <ul>
        {% for supplement in supplements %}
            <li>
                <a href="{% url 'supplements:supplement_detail' supplement.pk %}">{{ supplement.name }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>